export const authFormStyles = {
  container: {
    minHeight: '100vh',
    background: '#d7d7d7',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: '"Segoe UI", Arial, sans-serif',
    position: 'relative',
  },
  backBtn: {
    position: 'absolute',
    top: 24,
    left: 28,
    border: 0,
    background: 'transparent',
    color: '#28699e',
    fontSize: 46,
    lineHeight: 1,
    fontWeight: 300,
    cursor: 'pointer',
    padding: 0,
  },
  card: {
    width: 'min(420px, calc(100vw - 40px))',
    minHeight: 430,
    background: '#6390ba',
    borderRadius: 24,
    boxShadow: '0 10px 12px rgba(0, 0, 0, 0.24)',
    padding: '44px 48px 40px',
    boxSizing: 'border-box',
  },
  title: {
    margin: '0 0 54px',
    textAlign: 'center',
    color: '#f4f6fb',
    fontSize: 28,
    lineHeight: 1,
    fontWeight: 900,
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  field: {
    marginBottom: 24,
  },
  label: {
    display: 'block',
    margin: '0 0 8px 18px',
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 1,
    fontWeight: 800,
  },
  input: {
    width: '100%',
    height: 48,
    border: 0,
    borderRadius: 999,
    outline: 'none',
    background: '#dddddd',
    color: '#244f76',
    fontSize: 16,
    padding: '0 22px',
    boxSizing: 'border-box',
  },
  error: {
    color: '#ffe3e3',
    fontSize: 12,
    fontWeight: 700,
    margin: '5px 0 0 18px',
  },
  actions: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginTop: 44,
  },
  button: {
    width: 118,
    height: 38,
    border: 0,
    borderRadius: 999,
    background: '#dddddd',
    color: '#2f6f9c',
    fontSize: 14,
    fontWeight: 800,
    cursor: 'pointer',
  },
};
